apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: namespace-workflow-1671053601031
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080